
services:
  app:
    build:
      context: .  # Usa el Dockerfile en el directorio actual
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de la máquina host
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=6502
      - DATABASE_NAME=notes
      - DATABASE_PORT=5432
    depends_on:
      - database  # Asegura que la base de datos esté lista antes de iniciar la app
    networks:
      - app-network

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6502
      POSTGRES_DB: notes
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

# Define la red para que los servicios puedan comunicarse
networks:
  app-network:

# Define el volumen para mantener los datos de PostgreSQL
volumes:
  postgres-data: